<a href="https://colab.research.google.com/github/uyhawsugab/Python-Statistik/blob/main/TemplateSoal5_Matrik.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tugas Pemrograman Operasi Dasar Matrik**
*   NRP: 201111044
*   Nama: Wahyu Bagus Wicaksono
*   Kelas: D3
*   Kode Matakuliah: TI19KB11
*   Nama Matakuliah: Algoritma dan Pemrograman I
*   Tanggal Pengumpulan: 10 Desember 2020


---







**Soal Nomer 1 - Perkalian Dua Matriks**\
Buat program operasi dasar matrik yakni **penjumlahan dua matrik**, dimana ordo dan nilai dari kedua matriknya ditentukan oleh inputan user, flow programnya sbb:

1.   User mamasukkan ukuran ordo matrik pertama, misal a dan b
2.   User mamasukkan ukuran ordo matrik kedua, misal c dan d
3.   User memasukkan nilai dari matrik pertama sesuai dengan ordo matrik
4.   User memasukkan nilai dari matrik kedua sesuai dengan ordo matrik
5.   Program menampilkan proses perhitungan penjumlahan matrik
6.   Program menampilkan hasil perhitungan penjumlahan matrik
7.   Program menampilkan pertanyaan "Mau coba lagi?"
8.   Jika user menjawab Y maka program mulai lagi ke langkah 1, kalau tidak program selesai
















In [17]:
#Jawaban Soal Nomer 1

import numpy as np

ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

print()
print("Matriks 1")

outer_x = []
for i in range(ordo_y):
  inner_x = []
  for j in range(ordo_x):
    inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
    inner_x.append(inpt)
  outer_x.append(inner_x)

print()
print("Matriks 2")

outer_y = []
for i in range(ordo_y):
  inner_y = []
  for j in range(ordo_x):
    inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
    inner_y.append(inpt)
  outer_y.append(inner_y)

print()
print("Hasil Pemjumlahan dari Matriks 1 dan 2")

outer_z = []
for i in range(ordo_y):
  inner_z = []
  for j in range(ordo_x):
    inpt_z = outer_x[i][j] + outer_y[i][j]
    inner_z.append(inpt_z)
  outer_z.append(inner_z)

print()
print(np.array(outer_z))
print()

pilihan = input("Mau Coba Lagi ? : Y/N ")
print()

while pilihan == 'Y':
  ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
  ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

  print()
  print("Matriks 1")

  outer_x = []
  for i in range(ordo_y):
    inner_x = []
    for j in range(ordo_x):
      inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
      inner_x.append(inpt)
    outer_x.append(inner_x)

  print()
  print("Matriks 2")

  outer_y = []
  for i in range(ordo_y):
    inner_y = []
    for j in range(ordo_x):
      inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
      inner_y.append(inpt)
    outer_y.append(inner_y)

  print()
  print("Hasil Pemjumlahan dari Matriks 1 dan 2")

  outer_z = []
  for i in range(ordo_y):
    inner_z = []
    for j in range(ordo_x):
      inpt_z = outer_x[i][j] + outer_y[i][j]
      inner_z.append(inpt_z)
    outer_z.append(inner_z)

  print()
  print(np.array(outer_z))

  pilihan = input("Mau Coba Lagi ? : Y/N ")

print("Program Telah Selesai Dieksekusi")






Masukkan Jumlah Ordo X  : 2
Masukkan Jumlah Orde Y  : 2

Matriks 1
Masukkan nilai ke-0 dan ke-0 : 1
Masukkan nilai ke-0 dan ke-1 : 2
Masukkan nilai ke-1 dan ke-0 : 3
Masukkan nilai ke-1 dan ke-1 : 4

Matriks 2
Masukkan nilai ke-0 dan ke-0 : 4
Masukkan nilai ke-0 dan ke-1 : 3
Masukkan nilai ke-1 dan ke-0 : 2
Masukkan nilai ke-1 dan ke-1 : 1

Hasil Pemjumlahan dari Matriks 1 dan 2

[[5 5]
 [5 5]]

Mau Coba Lagi ? : Y/N N

Program Telah Selesai Dieksekusi


Jawaban Penjelasan program Soal Nomer 1


---



# **Penjelasan Program Nomer 1**

Pertama User akan menginputkan jumlah ordo dari tiap" Matriks, setelah di tentukan melalui input, setelah itu mendeklarasikan variabel penampung array pertama dan array kedua, setelah itu kita melakukan looping untuk memasukkan nilai ke dalam array, setelah semua nilai array terpenuhi, antara matriks X dan matriks Y, maka akan di lakukan perjumlahan untuk nilai dari matriks Z, dengan cara melooping isi dari matriks X dan Y kemudian di jumlahkan dan di masukkan ke dalam array matriks Z, setelah program di eksekusi, maka tersedia pilihan Y atau N, jika Y maka program akan di ulangi lagi, jika N maka program selesai di eksekusi


**Soal Nomer 2 Penjumlahan dan Pengurangan Matriks**\
Buat program operasi dasar matrik yakni **perkalian dua matrik**, dimana ordo dan nilai dari kedua matriknya ditentukan oleh inputan user, flow programnya sbb:

1.   User mamasukkan ukuran ordo matrik pertama, misal a dan b
2.   User mamasukkan ukuran ordo matrik kedua, misal c dan d
3.   User memasukkan nilai dari matrik pertama sesuai dengan ordo matrik
4.   User memasukkan nilai dari matrik kedua sesuai dengan ordo matrik
5.   Program menampilkan proses perhitungan perkalian matrik
6.   Program menampilkan hasil perhitungan perkalian matrik
7.   Program menampilkan pertanyaan "Mau coba lagi?"
8.   Jika user menjawab Y maka program mulai lagi ke langkah 1, kalau tidak program selesai


In [25]:
#Jawaban Soal Nomer 2

import numpy as np

ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

print()
print("Matriks 1")

outer_x = []
for i in range(ordo_y):
  inner_x = []
  for j in range(ordo_x):
    inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
    inner_x.append(inpt)
  outer_x.append(inner_x)

print()
print("Matriks 2")

outer_y = []
for i in range(ordo_y):
  inner_y = []
  for j in range(ordo_x):
    inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
    inner_y.append(inpt)
  outer_y.append(inner_y)
  
print()
print("Hasil Perkalian dari Matriks 1 dan 2")

outer_z = []
for i in range(0, len(outer_x)):
    inner_z = []
    for k in range(0, len(outer_x[0])):
        total = 0
        for j in range(ordo_x):
            total = total + (outer_x[i][j] * outer_y[j][k])
        inner_z.append(total)
    outer_z.append(inner_z)

print()
print(np.array(outer_z))

pilihan = input("Mau Coba Lagi ? : Y/N ")

while pilihan == 'Y':
  ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
  ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

  print()
  print("Matriks 1")

  outer_x = []
  for i in range(ordo_y):
    inner_x = []
    for j in range(ordo_x):
      inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
      inner_x.append(inpt)
    outer_x.append(inner_x)

  print()
  print("Matriks 2")

  outer_y = []
  for i in range(ordo_y):
    inner_y = []
    for j in range(ordo_x):
      inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
      inner_y.append(inpt)
    outer_y.append(inner_y)
    
  print()
  print("Hasil Perkalian dari Matriks 1 dan 2")

  outer_z = []
  for i in range(0, len(outer_x)):
      inner_z = []
      for k in range(0, len(outer_x[0])):
          total = 0
          for j in range(ordo_x):
              total = total + (outer_x[i][j] * outer_y[j][k])
          inner_z.append(total)
      outer_z.append(inner_z)

  print()
  print(np.array(outer_z))

  pilihan = input("Mau Coba Lagi ? : Y/N ")

print("Program Telah Selesai Dieksekusi")


Masukkan Jumlah Ordo X  : 2
Masukkan Jumlah Orde Y  : 2

Matriks 1
Masukkan nilai ke-0 dan ke-0 : 5
Masukkan nilai ke-0 dan ke-1 : 0
Masukkan nilai ke-1 dan ke-0 : 2
Masukkan nilai ke-1 dan ke-1 : 6

Matriks 2
Masukkan nilai ke-0 dan ke-0 : 1
Masukkan nilai ke-0 dan ke-1 : 0
Masukkan nilai ke-1 dan ke-0 : 2
Masukkan nilai ke-1 dan ke-1 : 4

Hasil Perkalian dari Matriks 1 dan 2

[[ 5  0]
 [14 24]]
Mau Coba Lagi ? : Y/N N
Program Telah Selesai Dieksekusi


Jawaban Penjelasan program Soal Nomer 2


---



# **Penjelasan Program Nomer 2**

Pertama User akan menginputkan jumlah ordo dari tiap" Matriks, setelah itu mendeklarasikan variabel penampung array pertama dan array kedua, setelah itu kita melakukan looping untuk memasukkan nilai ke dalam array, setelah semua nilai array terpenuhi, antara matriks X dan matriks Y, maka akan dilakukan looping, namun sebelum itu kita deklarasi array matriks z, setelah itu kita lakukan looping dengan range dari panjang array matriks x, dalam looping kita deklarasi array dalam array matriks z, itu bertujuan untuk menampung setiap nilai hasil dari perkalian antara matriks x dan y, setelah itu kita print matriks z, setelah hasil dari matriks z keluar user diberikan pilihan berupa Y atau N, jika Y maka program akan terus di eksekusi jika N maka program akan berakhir

**Soal Nomer 3 - Perkalian Matriks Dengan Bilangan Bulat atau Perkalian Skalar Matriks**
Buat program operasi dasar matrik yakni **perkalian skalar matrik**, dimana nilai skalar(bilangan bulat), ordo dan nilai dari matriknya ditentukan oleh inputan user, flow programnya sbb:
1.   User mamasukkan nilai skalarnya, misal a
2.   User mamasukkan ukuran ordo matrik, misal c dan d
3.   User memasukkan nilai dari matrik sesuai dengan ordo matrik
4.   Program menampilkan proses perhitungan perkalian matrik
5.   Program menampilkan hasil perhitungan perkalian matrik
6.   Program menampilkan pertanyaan "Mau coba lagi?"
7.   Jika user menjawab Y maka program mulai lagi ke langkah 1, kalau tidak program selesai

In [26]:
#Jawaban Soal Nomer 3

import numpy as np

skalar = int(input("Masukkan Bilangan Bulat : "))
ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

print()
print("Matriks 1")

outer_x = []
for i in range(ordo_y):
  inner_x = []
  for j in range(ordo_x):
    inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
    inner_x.append(inpt)
  outer_x.append(inner_x)


print()
print("Hasil Perkalian dari Skalar dan Matriks")

outer_z = []
for i in range(0, len(outer_x)):
    inner_z = []
    total = 0
    for j in range(0, len(outer_x)):
      total = skalar * outer_x[i][j]
      inner_z.append(total)
    outer_z.append(inner_z)

print()
print(np.array(outer_z))

pilihan = input("Mau Coba Lagi ? : Y/N ")

while pilihan == 'Y':
  skalar = int(input("Masukkan Bilangan Bulat : "))
  ordo_x = int(input("Masukkan Jumlah Ordo X  : "))
  ordo_y = int(input("Masukkan Jumlah Orde Y  : "))

  print()
  print("Matriks 1")

  outer_x = []
  for i in range(ordo_y):
    inner_x = []
    for j in range(ordo_x):
      inpt = int(input("Masukkan nilai ke-{} dan ke-{} : ".format(i,j)))
      inner_x.append(inpt)
    outer_x.append(inner_x)


  print()
  print("Hasil Perkalian dari Skalar dan Matriks")

  outer_z = []
  for i in range(0, len(outer_x)):
      inner_z = []
      total = 0
      for j in range(0, len(outer_x)):
        total = skalar * outer_x[i][j]
        inner_z.append(total)
      outer_z.append(inner_z)

  print()
  print(np.array(outer_z))

  pilihan = input("Mau Coba Lagi ? : Y/N ")

print("Program Telah Selesai Dieksekusi")

Masukkan Bilangan Bulat : 2
Masukkan Jumlah Ordo X  : 2
Masukkan Jumlah Orde Y  : 2

Matriks 1
Masukkan nilai ke-0 dan ke-0 : 1
Masukkan nilai ke-0 dan ke-1 : 2
Masukkan nilai ke-1 dan ke-0 : 3
Masukkan nilai ke-1 dan ke-1 : 4

Hasil Perkalian dari Skalar dan Matriks

[[2 4]
 [6 8]]
Mau Coba Lagi ? : Y/N N
Program Telah Selesai Dieksekusi


Jawaban Penjelasan program Soal Nomer 3


---



# **Penjelasan Program Nomer 3**

Pertama User akan menginputkan jumlah ordo dari Matriks dan juga menginputkan bilangan skalar, setelah itu mendeklarasikan variabel penampung array matriks x dan matriks z, kemudian melakukan looping untuk menginputkan isi dari variabel array matriks x, setelah user selesai melakukan input, maka akan dilakukan looping untuk melakukan perkalian dari nilai skalar dan matriks x, setelah selesai melakukan looping maka nilai dari looping tadi langsung di masukkan kedalam array matriks z, kemudian matriks z di print, di akhir program user mendapakan pilihan berupa Y atau N, jika Y maka program akan di ulang terus, jika N maka program telah selesai di eksekusi